### ISSUE TITLE
Drupal 7 Migration Issue: %entity_object removed from Backdrop's entity integration.

### ISSUE THREAD

**Issue by rbargerhuff** [backdrop-contrib/entity_ui#14] opened 2022-08-29 17:34 UTC
entity_object_load() that was defined in the entity_api module has been removed. This causes issues with any URL paths that contain  `%entity_object`. The solution would be to define the following within the entity_ui module.

 ```
/**
 * Menu loader function: load an entity from its path.
 *
 * This can be used to load entities of all types in menu paths:
 *
 * @code
 * $items['myentity/%entity_object'] = array(
 *   'load arguments' => array('myentity'),
 *   'title' => ...,
 *   'page callback' => ...,
 *   'page arguments' => array(...),
 *   'access arguments' => array(...),
 * );
 * @endcode
 *
 * @param $entity_id
 *   The ID of the entity to load, passed by the menu URL.
 * @param $entity_type
 *   The type of the entity to load.
 * @return
 *   A fully loaded entity object, or FALSE in case of error.
 */
function entity_ui_object_load($id, $entity_type) {
  return entity_load($entity_type, $id);
}
 ```

**Comment by argiepiano** [comment] 2022-08-29 18:35
`entity_ui_object_load(x, y)` already exists.  See: 
https://github.com/backdrop-contrib/entity_ui/blob/77f1ddadefb043a081fde9c82d5a749ce16dbcf6/entity_ui.module#L70

But the problem is that the auto-loader then has to be `%entity_ui_object`. Perhaps that's a good compromise - meaning that you'd need to modify those menu items from `%entity_object` to `%entity_ui_object`

~~Otherwise you can use the core loader `%entity` which will invoke `entity_load()` with the same result.~~

**Comment by argiepiano** [comment] 2022-08-29 18:38
Actually, I have to edit this last part of my response - `%entity` may actually not work , as `entity_load()` requires the entity type as the first parameter, which is problematic when working with a menu item object loader.

But `%entity_ui_object` should work fine

**Comment by rbargerhuff** [comment] 2022-08-29 19:47
Okay. That'll work. However, references to `%entity_object` is still being referenced in entity_ui module.

_entity_ui.inc: Line 433:_

`EntityContentUIController: public function hook_menu() {`

`$wildcard = isset($this->entityInfo['admin ui']['menu wildcard']) ? $this->entityInfo['admin ui']['menu wildcard'] : '%entity_object';`

**Comment by rbargerhuff** [comment] 2022-08-29 19:53
I had to update my comment to provide the code that is referencing `%entity_object`.

**Comment by rbargerhuff** [comment] 2022-08-29 20:11
My suggestion for function `entity_ui_object_load()`

```
/**
 * Menu loader function: load an entity from its path.
 *
 * This can be used to load entities of all types in menu paths:
 *
 * @code
 * $items['myentity/%entity_object'] = array(
 *   'load arguments' => array('myentity'),
 *   'title' => ...,
 *   'page callback' => ...,
 *   'page arguments' => array(...),
 *   'access arguments' => array(...),
 * );
 * @endcode
 *
 * @param $entity_id
 *   The ID of the entity to load, passed by the menu URL.
 * @param $entity_type
 *   The type of the entity to load.
 * @return
 *   A fully loaded entity object, or FALSE in case of error.
 */
function entity_ui_object_load($entity_id, $entity_type) {
  $entity = entity_load($entity_type, $entity_id);
  return entity;
}
```

**Comment by argiepiano** [comment] 2022-08-30 01:33
Good catch about the reference to `%entity_object`! I've also followed your suggestion regarding the code in `entity_ui_object_load()`. 
PR #15 

I will merge so that you can test.

It works for me in my testing with a custom entity that uses the `%entity_ui_object` loader.

**Comment by argiepiano** [comment] 2022-08-30 01:34
Reopening this issue after merging  to encourage  testing of the dev version.

**Comment by rbargerhuff** [comment] 2022-08-30 15:16
Thanks for getting that merged. I have successfully tested the changes and I see no issues on our end.

**Comment by argiepiano** [comment] 2022-09-06 01:34
Closing this issue. New version that includes this fix has been released.

**Closed as completed by argiepiano** 2022-09-06 01:34 UTC
